name: Auto Update README

on:
  push:
    paths:
      - '**/'         # trigger on folder additions
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate README
        run: |
          node .github/scripts/updateReadme.js

      - name: Commit and Push if Changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --staged --quiet || git commit -m "Auto-update README with new folders"
          git push
